# Generated by Django 2.0.4 on 2018-04-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc', models.IntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=10)),
                ('creature_type', models.CharField(max_length=250)),
                ('losses', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('power', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('title', models.TextField()),
                ('toughness', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=100)),
                ('revision', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Deck_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_revision_added', models.IntegerField()),
                ('deck_revision_removed', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckManager.Card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckManager.Deck')),
            ],
        ),
    ]
