# Generated by Django 2.0.4 on 2018-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.CharField(max_length=10),
        ),
    ]
